// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using jira.Data;

#nullable disable

namespace jira.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609125650_AddOAuthFields")]
    partial class AddOAuthFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("jira.DbModels.Komentarz", b =>
                {
                    b.Property<int>("IdKomentarza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_komentarza");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdKomentarza"));

                    b.Property<DateTime?>("DataEdycji")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_edycji");

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_utworzenia");

                    b.Property<int>("IdUzytkownika")
                        .HasColumnType("integer")
                        .HasColumnName("id_uzytkownika");

                    b.Property<int>("IdZadania")
                        .HasColumnType("integer")
                        .HasColumnName("id_zadania");

                    b.Property<string>("TrescKomentarza")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tresc_komentarza");

                    b.HasKey("IdKomentarza");

                    b.HasIndex("IdUzytkownika");

                    b.HasIndex("IdZadania");

                    b.ToTable("KOMENTARZE");
                });

            modelBuilder.Entity("jira.DbModels.Tablica", b =>
                {
                    b.Property<int>("IdTablicy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tablicy");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTablicy"));

                    b.Property<DateTime>("DataStworzenia")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_stworzenia");

                    b.Property<int>("IdUzytkownikaOwner")
                        .HasColumnType("integer")
                        .HasColumnName("id_uzytkownika_owner");

                    b.Property<string>("KolorTablicy")
                        .HasColumnType("text")
                        .HasColumnName("kolor_tablicy");

                    b.Property<string>("NazwaTablicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazwa_tablicy");

                    b.Property<string>("OpisTablicy")
                        .HasColumnType("text")
                        .HasColumnName("opis_tablicy");

                    b.HasKey("IdTablicy");

                    b.HasIndex("IdUzytkownikaOwner");

                    b.ToTable("TABLICE");
                });

            modelBuilder.Entity("jira.DbModels.TablicaUzytkownik", b =>
                {
                    b.Property<int>("IdUzytkownika")
                        .HasColumnType("integer")
                        .HasColumnName("id_uzytkownika");

                    b.Property<int>("IdTablicy")
                        .HasColumnType("integer")
                        .HasColumnName("id_tablicy");

                    b.Property<DateTime>("DataDolaczenia")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_dolaczenia");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rola");

                    b.HasKey("IdUzytkownika", "IdTablicy");

                    b.HasIndex("IdTablicy");

                    b.ToTable("TABLICE_UZYTKOWNICY");
                });

            modelBuilder.Entity("jira.DbModels.Uzytkownik", b =>
                {
                    b.Property<int>("IdUzytkownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_uzytkownika");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUzytkownika"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("DataRejestracji")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_rejestracji");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GitHubId")
                        .HasColumnType("text")
                        .HasColumnName("github_id");

                    b.Property<string>("GitHubRefreshTokenEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("github_refresh_token_encrypted");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<string>("GoogleRefreshTokenEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("google_refresh_token_encrypted");

                    b.Property<string>("NazwaUzytkownika")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazwa_uzytkownika");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("IdUzytkownika");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UZYTKOWNICY");
                });

            modelBuilder.Entity("jira.DbModels.Zadanie", b =>
                {
                    b.Property<int>("IdZadania")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_zadania");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdZadania"));

                    b.Property<DateTime>("DataStworzenia")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_stworzenia");

                    b.Property<DateTime?>("DataZakonczenia")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_zakonczenia");

                    b.Property<int>("IdTablicy")
                        .HasColumnType("integer")
                        .HasColumnName("id_tablicy");

                    b.Property<int?>("IdUzytkownikaPrzypisanego")
                        .HasColumnType("integer")
                        .HasColumnName("id_uzytkownika_przypisanego");

                    b.Property<int>("IdUzytkownikaTworcyZadania")
                        .HasColumnType("integer")
                        .HasColumnName("id_uzytkownika_tworcy_zadania");

                    b.Property<string>("KolumnaTablicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kolumna_tablicy");

                    b.Property<string>("OpisZadania")
                        .HasColumnType("text")
                        .HasColumnName("opis_zadania");

                    b.Property<string>("Priorytet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priorytet");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TytulZadania")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tytul_zadania");

                    b.HasKey("IdZadania");

                    b.HasIndex("IdTablicy");

                    b.HasIndex("IdUzytkownikaPrzypisanego");

                    b.HasIndex("IdUzytkownikaTworcyZadania");

                    b.ToTable("ZADANIA");
                });

            modelBuilder.Entity("jira.DbModels.Komentarz", b =>
                {
                    b.HasOne("jira.DbModels.Uzytkownik", "Uzytkownik")
                        .WithMany("Komentarze")
                        .HasForeignKey("IdUzytkownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("jira.DbModels.Zadanie", "Zadanie")
                        .WithMany("Komentarze")
                        .HasForeignKey("IdZadania")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");

                    b.Navigation("Zadanie");
                });

            modelBuilder.Entity("jira.DbModels.Tablica", b =>
                {
                    b.HasOne("jira.DbModels.Uzytkownik", "Owner")
                        .WithMany("TabliceOwner")
                        .HasForeignKey("IdUzytkownikaOwner")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("jira.DbModels.TablicaUzytkownik", b =>
                {
                    b.HasOne("jira.DbModels.Tablica", "Tablica")
                        .WithMany("TabliceUzyt")
                        .HasForeignKey("IdTablicy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("jira.DbModels.Uzytkownik", "Uzytkownik")
                        .WithMany("TabliceUzyt")
                        .HasForeignKey("IdUzytkownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tablica");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("jira.DbModels.Zadanie", b =>
                {
                    b.HasOne("jira.DbModels.Tablica", "Tablica")
                        .WithMany("Zadania")
                        .HasForeignKey("IdTablicy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("jira.DbModels.Uzytkownik", "UzytkownikPrzypisany")
                        .WithMany("ZadaniaPrzypisane")
                        .HasForeignKey("IdUzytkownikaPrzypisanego")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("jira.DbModels.Uzytkownik", "TworcaZadania")
                        .WithMany("ZadaniaStworzone")
                        .HasForeignKey("IdUzytkownikaTworcyZadania")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tablica");

                    b.Navigation("TworcaZadania");

                    b.Navigation("UzytkownikPrzypisany");
                });

            modelBuilder.Entity("jira.DbModels.Tablica", b =>
                {
                    b.Navigation("TabliceUzyt");

                    b.Navigation("Zadania");
                });

            modelBuilder.Entity("jira.DbModels.Uzytkownik", b =>
                {
                    b.Navigation("Komentarze");

                    b.Navigation("TabliceOwner");

                    b.Navigation("TabliceUzyt");

                    b.Navigation("ZadaniaPrzypisane");

                    b.Navigation("ZadaniaStworzone");
                });

            modelBuilder.Entity("jira.DbModels.Zadanie", b =>
                {
                    b.Navigation("Komentarze");
                });
#pragma warning restore 612, 618
        }
    }
}
