name: automatic-test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  CI-CD-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: zainstaluj .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: przywracanie zależności
        working-directory: ./jira
        run: dotnet restore

      - name: kompilacja głównego projektu (Build)
        working-directory: ./jira
        run: dotnet build

      - name: uruchomienie testów (Tests) + coverage
        working-directory: ./jira.Tests
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory ./wynikitestu

      - name: pobranie coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            ./jira.Tests/wynikitestu/**/coverage.cobertura.xml

